### PR TITLE
[finishes #162955835] created profile page

### PR DESCRIPTION
**Pull request by stanozzy**
**What does this PR do?**
This PR allows users to view their profile 
**Description of the Task to be completed**

- Write HTML for the profile page
- Write CSS for the profile page

**How should this be manually tested?**

- clone this repository to your local machine:
`https://github.com/stanozzy/Questioner-UI.git `
- git checkout to this branch
`ft-162955835-profile`
- open profile.html in your preferred browser.

**Pivotal tracker story associated with this PR:**
`#162955835`
**screenshot:**
screenshot from 2019-01-05 21-09-45

### CODE REVIEW

**Comment by wachiranduati** [comment]
Awesome UI

**Comment by wachiranduati** [comment]
Awesome UI

**Comment by JosephNjuguna** [comment]
nice

**Comment by stanozzy** [comment]
Thanks

**Pull request merged**
