### PR TITLE
[finishes #162955611] created sign-up page

### PR DESCRIPTION
**Pull request by stanozzy**
**What does this PR do?**
This PR allows users to create a Quesioner account
**Description of the Task to be completed**

- Write HTML for the sign up page
- Write CSS for the sign up page

**How should this be manually tested?**

- clone this repository to your local machine:
`https://github.com/stanozzy/Questioner-UI.git `
- git checkout to this branch
`ft-162955611-sign-up`
- open sign-up.html in your preferred browser.

**Pivotal tracker story associated with this PR:**
`#162955611`
**screenshot:**
screenshot from 2019-01-05 12-37-50

### CODE REVIEW

**Comment by luqee** [comment]
This is a nice intuitive interface.

**Comment by stanozzy** [comment]
Thanks luqee

**Comment by JosephNjuguna** [comment]
nice..

**Comment by stanozzy** [comment]
Thanks

**Pull request merged**
